name: epub_generator
description: A Flutter app that scrapes web novels and converts them into EPUB and Word files.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  logging: ^1.0.2
  dio: ^5.4.0
  html: ^0.15.4
  epubx: ^4.0.0
  share_plus: ^4.0.0
  cross_file: ^0.3.3
  provider: ^6.1.3
  archive: ^3.3.0
  file_picker: ^5.2.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true