name: epub_generator
description: A Flutter app that scrapes web novels and converts them into EPUB files.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests and web scraping
  dio: ^5.4.0
  html: ^0.15.4

  # EPUB creation
  epubx: ^4.0.0

  # Path management
  path_provider: ^2.1.1

  # State management (optional, for better architecture)
  provider: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
